/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eldenark;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author cep
 */
public class EquipmentFrame extends javax.swing.JFrame {

	private final String path = "/FOTOS ELDEN ARK/EQUIPMENT/"; 
	private String helmetPath;
	private String chestPath;
	private String legPath;
	private String weaponPath;
	private String weaponString;
	private String helmetString;
	private String chestString;
	private String legString;
	private String weaponHover;
	private String helmetHover;
	private String chestHover;
	private String legHover;
	Character mainCharacter;
	JLabel[] background = new JLabel[4];
	/**
	 * Creates new form EquipmentFrame
	 */
	public EquipmentFrame(Character mainCharacter) {
		this.mainCharacter = mainCharacter;
		setInformation();
		setCorrectPath();
		initComponents();
		
		background();
		this.getContentPane().setBackground(Color.DARK_GRAY);
	}
	
	private void setInformation(){
		weaponString = mainCharacter.getEquipment()[0].getName();
		helmetString = mainCharacter.getEquipment()[1].getName();
		chestString = mainCharacter.getEquipment()[2].getName();
		legString  = mainCharacter.getEquipment()[3].getName();
		weaponHover = "+" + mainCharacter.getEquipment()[0].getProfit() + " damage";
		helmetHover = "+" + mainCharacter.getEquipment()[1].getProfit() + " defence";
		chestHover = "+" + mainCharacter.getEquipment()[2].getProfit() + " defence";
		legHover = "+" + mainCharacter.getEquipment()[3].getProfit() + " defence";
	
	} 
	
	private void background(){
		for (int i = 0; i < background.length; i++) {
			background[i] = new JLabel();
			this.add(background[i]);
			background[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTOS ELDEN ARK/weapon background.png")));
	
		}
		background[0].setBounds(Chest.getX(), Chest.getY(), 90, 90);
		background[1].setBounds(Weapon.getX(), Weapon.getY(), 90, 90);
		background[2].setBounds(Helmet.getX(), Helmet.getY(), 90, 90);
		background[3].setBounds(Leg.getX(), Leg.getY(), 90, 90);
	}
	
	private void setCorrectPath(){
		
		weaponPath = path.concat(mainCharacter.getClass().getName().substring(9) + "/" + mainCharacter.getEquipment()[0].getName() + ".png");
		helmetPath = path.concat(mainCharacter.getClass().getName().substring(9) + "/" + mainCharacter.getEquipment()[1].getName() + ".png");
		chestPath = path.concat(mainCharacter.getClass().getName().substring(9) + "/" + mainCharacter.getEquipment()[2].getName() + ".png");
		legPath = path.concat(mainCharacter.getClass().getName().substring(9) + "/" + mainCharacter.getEquipment()[3].getName() + ".png");
		
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Weapon = new javax.swing.JLabel();
        Helmet = new javax.swing.JLabel();
        Chest = new javax.swing.JLabel();
        Leg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equipment");
        setMaximumSize(new java.awt.Dimension(500, 464));
        setMinimumSize(new java.awt.Dimension(500, 464));

        Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource(weaponPath)));
        Weapon.setToolTipText(weaponHover);

        Helmet.setIcon(new javax.swing.ImageIcon(getClass().getResource(helmetPath)));
        Helmet.setToolTipText(helmetHover);

        Chest.setIcon(new javax.swing.ImageIcon(getClass().getResource(chestPath)));
        Chest.setToolTipText(chestHover);

        Leg.setIcon(new javax.swing.ImageIcon(getClass().getResource(legPath)));
        Leg.setToolTipText(legHover);
        Leg.setMaximumSize(new java.awt.Dimension(600, 600));
        Leg.setMinimumSize(new java.awt.Dimension(600, 600));
        Leg.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(weaponString);
        jLabel1.setToolTipText(weaponString);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(helmetString);
        jLabel2.setToolTipText(helmetString);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(chestString);
        jLabel3.setToolTipText(chestString);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(legString);
        jLabel4.setToolTipText(legString);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Chest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Helmet, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Helmet, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chest, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EquipmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EquipmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EquipmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EquipmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new EquipmentFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chest;
    private javax.swing.JLabel Helmet;
    private javax.swing.JLabel Leg;
    private javax.swing.JLabel Weapon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
